
spring:
  datasource:
    password: pzy741
    username: root
    url: jdbc:mysql://inmeyu.com:3306/abdts_mainsys?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jmx:
    default-domain: search
mybatis:
  mapper-locations:
      - mybatis1/mapper/*/*.xml
  type-aliases-package:
      com.abdts